server:
  port: 7001
spring:
  application:
    name: mall-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: zjd
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall-pms?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false

mybatis-plus:
  mapper-locations: classpath:mapper/product/*.xml
  type-aliases-package: com.zzz.cloud.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
logging:
  level:
    com.zzz.product: debug